workflows:
  android-workflow:
    name: Android Build

    scripts:
      - |
          cd client
          npm install
          npm run build
          npx cap sync android
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

    artifacts:
      - client/android/app/build/outputs/apk/debug/*.apk